/* eslint-disable @typescript-eslint/no-var-requires */
/* eslint-disable @typescript-eslint/ban-ts-comment */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [{ type: "autogenerated", dirName: "." }],
  // reference: [
  //   {
  //     type: "doc",
  //     id: "reference",
  //   },
  //   {
  //     type: "category",
  //     label: "Contracts",
  //     link: {
  //       type: "doc",
  //       id: "reference/contracts",
  //     },
  //     collapsed: true,
  //     items: [
  //       {
  //         type: "doc",
  //         id: "reference/contracts/identity",
  //       },
  //       {
  //         type: "category",
  //         label: "Bridge Protocol Contracts",
  //         link: {
  //           type: "doc",
  //           id: "reference/contracts/bridge",
  //         },
  //         collapsed: false,
  //         items: [
  //           "reference/contracts/bridge/evm",
  //           "reference/contracts/bridge/near",
  //           "reference/contracts/bridge/solana",
  //         ],
  //       },
  //     ],
  //   },
  //   {
  //     type: "doc",
  //     id: "reference/proof-of-humanity",
  //   },
  //   {
  //     type: "doc",
  //     id: "reference/polygonid-state-replication",
  //   },
  //   {
  //     type: "doc",
  //     id: "reference/api",
  //   },
  //   {
  //     type: "category",
  //     label: "JavaScript SDK",
  //     link: {
  //       type: "doc",
  //       id: "reference/sdk",
  //     },
  //     collapsed: true,
  //     items: [
  //       "reference/sdk/packages-base",
  //       "reference/sdk/packages-provider",
  //       "reference/sdk/packages-bridge",
  //       "reference/sdk/packages-identity",
  //     ],
  //   },
  //   {
  //     type: "category",
  //     label: "Core",
  //     link: {
  //       type: "doc",
  //       id: "reference/core",
  //     },
  //     collapsed: true,
  //     items: [
  //       "reference/core/rarimocore",
  //       "reference/core/tokenmanager",
  //       "reference/core/oraclemanager",
  //       "reference/core/tss",
  //       "reference/core/oracles",
  //     ],
  //   },
  //   {
  //     type: "doc",
  //     id: "reference/audits",
  //   },
  //   {
  //     type: "doc",
  //     id: "reference/glossary",
  //   },
  // ],
};

module.exports = sidebars;
